
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author surya
 */
public class ConversionApplicationInGui extends javax.swing.JFrame {

    /**
     * Creates new form ConversionApplicationInGui
     */
    public ConversionApplicationInGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        convert1 = new javax.swing.JButton();
        convert2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jToggleButton3 = new javax.swing.JToggleButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField11 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        convert3 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(80, 109, 250));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton1.setText("ON/OFF");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 109, -1));

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton2.setText("ON/OFF");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, -1, -1));

        jTextField1.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 290, 50));

        jTextField2.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 314, 50));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 290, 49));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 320, 50));

        convert1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        convert1.setText("Convert");
        convert1.setEnabled(false);
        convert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert1ActionPerformed(evt);
            }
        });
        getContentPane().add(convert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        convert2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        convert2.setText("Convert");
        convert2.setEnabled(false);
        convert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert2ActionPerformed(evt);
            }
        });
        getContentPane().add(convert2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, -1, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 193, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Kelvin", "Celsius" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        jTextField5.setBackground(new java.awt.Color(250, 250, 250));
        jTextField5.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 365, 50));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 365, 49));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Exit\n");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 620, 120, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 100, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, 110, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("All Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 620, 120, 30));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(78, 5, 88));
        jTextField7.setText("Developed By SURYA R");
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 170, 30));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miles", "Km", "Meter" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 128, 38));

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Km", "Miles", "Meter" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 128, 38));

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton3.setText("ON/OFF");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Grams", "Pounds" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 144, 34));

        jComboBox6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grams", "Kg", "Pounds" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, 135, 33));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(250, 250, 0));
        jTextField11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 0, 1));
        jTextField11.setText("Conversion Calculator");
        jTextField11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jTextField11.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 36, 370, -1));

        jDesktopPane1.setBackground(new java.awt.Color(128, 128, 128));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Modern No. 20", 1, 34)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("Length Converter");

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Modern No. 20", 1, 34)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("Temperature Converter");

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Modern No. 20", 1, 34)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("Mass Converter");

        jDesktopPane1.setLayer(jTextField9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField9)
                    .addComponent(jTextField10)
                    .addComponent(jTextField12))
                .addContainerGap())
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 1050, 60));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 92, 30));

        convert3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        convert3.setText("Convert ");
        convert3.setEnabled(false);
        convert3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert3ActionPerformed(evt);
            }
        });
        getContentPane().add(convert3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 110, -1));

        jTextField8.setBackground(new java.awt.Color(250, 250, 250));
        jTextField8.setForeground(new java.awt.Color(99, 99, 78));
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 46));
        jTextField8.setCaretColor(new java.awt.Color(145, 89, 123));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1180, 670));

        jMenu3.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(1187, 688));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if(jToggleButton1.isSelected()){
        jTextField1.setEnabled(true);
        jTextField3.setEnabled(true);
        convert1.setEnabled(true);
        }
        else{
        jTextField1.setEnabled(false);
        jTextField3.setEnabled(false);
        convert1.setEnabled(false);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if(jToggleButton2.isSelected()){
        jTextField2.setEnabled(true);
        jTextField4.setEnabled(true);
        convert2.setEnabled(true);
        }
        else{
        jTextField2.setEnabled(false);
        jTextField4.setEnabled(false);
        convert2.setEnabled(false);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void convert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert1ActionPerformed
       String box3 = (String)jComboBox3.getSelectedItem();
        String box4 = (String)jComboBox4.getSelectedItem();
        
        if(box3.equals("Miles") && box4.equals("Km"))
        {
            double Miles = Double.parseDouble(jTextField1.getText());
            
            double Km = (double) (1.609344*Miles);
            
            jTextField3.setText(String.valueOf(Km));
        }    
        if(box3.equals("Miles") && box4.equals("Meter"))
        {
            double Miles = Double.parseDouble(jTextField1.getText());
            
            double Meter = (double) (1609.34*Miles);
            
            jTextField3.setText(String.valueOf(Meter));
        }
        if(box3.equals("Miles") && box4.equals("Miles"))
        {
            double Miles = Double.parseDouble(jTextField1.getText());
           
            jTextField3.setText(String.valueOf(Miles));
        }
        //----------------------------------------------------------------------
        if(box3.equals("Km") && box4.equals("Miles"))
       {
           double Km = Double.parseDouble(jTextField1.getText());
           
           double Miles = (double)(0.621371*Km);
           
           jTextField3.setText(String.valueOf(Miles));
       }
       else if(box3.equals("Km") && box4.equals("Meter"))
       {
           double Km = Double.parseDouble(jTextField1.getText());
           
           double Meter = (double)(1000*Km);
           
           jTextField3.setText(String.valueOf(Meter));
       }
       else if(box3.equals("Km") && box4.equals("Km"))
       {
           double Km = Double.parseDouble(jTextField1.getText());
         
           jTextField3.setText(String.valueOf(Km));
       }
        //----------------------------------------------------------------------
         if(box3.equals("Meter") && box4.equals("Miles"))
       {
           double Meter = Double.parseDouble(jTextField1.getText());
           
           double Miles = (double)(0.000621371*Meter);  
           
            jTextField3.setText(String.valueOf(Miles));
       }
        else if(box3.equals("Meter") && box4.equals("Km"))
       {
           double Meter = Double.parseDouble(jTextField1.getText());
           
           double Km = (double)(0.001*Meter);
           
           jTextField3.setText(String.valueOf(Km));
       }
         else if(box3.equals("Meter") && box4.equals("Meter"))
       {
           double Meter = Double.parseDouble(jTextField1.getText());
         
           jTextField3.setText(String.valueOf(Meter));
       }
    }//GEN-LAST:event_convert1ActionPerformed

    private void convert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert2ActionPerformed
        String box5 = (String)jComboBox5.getSelectedItem();
        String box6 = (String)jComboBox6.getSelectedItem();
        
        if(box5.equals("Kg") && box6.equals("Grams"))
        {
            double Kg = Double.parseDouble(jTextField2.getText());
            
            double Grams = (double) (1000*Kg);
            
            jTextField4.setText(String.valueOf(Grams));
        }    
        if(box5.equals("Kg") && box6.equals("Pounds"))
        {
            double Kg = Double.parseDouble(jTextField2.getText());
            
            double Pounds = (double) (2.20462*Kg);
            
            jTextField4.setText(String.valueOf(Pounds));
        }
        if(box5.equals("Kg") && box6.equals("Kg"))
        {
            double Kg = Double.parseDouble(jTextField2.getText());
           
            jTextField4.setText(String.valueOf(Kg));
        }
        //----------------------------------------------------------------------
        if(box5.equals("Grams") && box6.equals("Kg"))
       {
           double Grams = Double.parseDouble(jTextField2.getText());
           
           double Kg = (double)(0.001*Grams);
           
           jTextField4.setText(String.valueOf(Kg));
       }
       else if(box5.equals("Grams") && box6.equals("Pounds"))
       {
           double Grams = Double.parseDouble(jTextField2.getText());
           
           double Pounds = (double)(0.00220462*Grams);
           
           jTextField4.setText(String.valueOf(Pounds));
       }
       else if(box5.equals("Grams") && box6.equals("Grams"))
       {
           double Grams = Double.parseDouble(jTextField2.getText());
         
           jTextField4.setText(String.valueOf(Grams));
       }
        //----------------------------------------------------------------------
         if(box5.equals("Pounds") && box6.equals("Kg"))
       {
           double Pounds = Double.parseDouble(jTextField2.getText());
           
           double Kg = (double)(0.453592*Pounds);  
           
            jTextField4.setText(String.valueOf(Kg));
       }
        else if(box5.equals("Pounds") && box6.equals("Grams"))
       {
           double Pounds = Double.parseDouble(jTextField2.getText());
           
           double Grams = (double)(453.592*Pounds);
           
           jTextField4.setText(String.valueOf(Grams));
       }
         else if(box5.equals("Pounds") && box6.equals("Pounds"))
       {
           double Pounds = Double.parseDouble(jTextField2.getText());
         
           jTextField4.setText(String.valueOf(Pounds));
       }
    }//GEN-LAST:event_convert2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void convert3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert3ActionPerformed
        String box1 = (String)jComboBox1.getSelectedItem();
        String box2 = (String)jComboBox2.getSelectedItem();
        
        if(box1.equals("Celsius") && box2.equals("Fahrenheit"))
        {
            double c = Double.parseDouble(jTextField5.getText());
            
            double f = (double) (c * 1.8 + 32);
            
            jTextField6.setText(String.valueOf(f));
        }    
        if(box1.equals("Celsius") && box2.equals("Kelvin"))
        {
            double c = Double.parseDouble(jTextField5.getText());
            
            double k = (double) (c + 273.15);
            
            jTextField6.setText(String.valueOf(k));
        }
        if(box1.equals("celsius") && box2.equals("Celsius"))
        {
            double c = Double.parseDouble(jTextField5.getText());
           
            jTextField6.setText(String.valueOf(c));
        }
        //----------------------------------------------------------------------
        if(box1.equals("Fahrenheit") && box2.equals("Celsius"))
       {
           double f = Double.parseDouble(jTextField5.getText());
           
           double c = (double)((f - 32)*5/9);
           
           jTextField6.setText(String.valueOf(c));
       }
       else if(box1.equals("Fahrenheit") && box2.equals("Kelvin"))
       {
           double f = Double.parseDouble(jTextField5.getText());
           
           double k = (double)((f - 32)*5/9 + 273.15);
           
           jTextField6.setText(String.valueOf(k));
       }
       else if(box1.equals("Fahrenheit") && box2.equals("Fahrenheit"))
       {
           double f = Double.parseDouble(jTextField5.getText());
         
           jTextField6.setText(String.valueOf(f));
       }
        //----------------------------------------------------------------------
         if(box1.equals("Kelvin") && box2.equals("Celsius"))
       {
           double k = Double.parseDouble(jTextField5.getText());
           
           double c = (double)(0 - 273.15);  
           
            jTextField6.setText(String.valueOf(c));
       }
        else if(box1.equals("Kelvin") && box2.equals("Fahrenheit"))
       {
           double k = Double.parseDouble(jTextField5.getText());
           
           double f = (double)(0 - 273.15) * 9/5 +32;
           
           jTextField6.setText(String.valueOf(f));
       }
         else if(box1.equals("Kelvin") && box2.equals("Kelvin"))
       {
           double k = Double.parseDouble(jTextField5.getText());
         
           jTextField6.setText(String.valueOf(k));
       }
         
    
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_convert3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField5.setText("");
        jTextField6.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFrame frame = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want Exit", "EXIT", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField1.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextField2.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JFrame frame;
        frame = new JFrame("");
        if(JOptionPane.showConfirmDialog(frame,"Are You Sure Want To Clear All", "", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        if(jToggleButton3.isSelected()){
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);
            convert3.setEnabled(true);
        }
        else{
            jTextField5.setEnabled(false);
            jTextField6.setEnabled(false);
            convert3.setEnabled(false);
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversionApplicationInGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversionApplicationInGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversionApplicationInGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversionApplicationInGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversionApplicationInGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convert1;
    private javax.swing.JButton convert2;
    private javax.swing.JButton convert3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
